src/plots/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('abspl', views.abspl, name='abspl'),
    path('pxrd', views.xrd, name='xrd'),
    path('ftir', views.ftir, name='ftir'),
    path('plqy', views.plqy, name='plqy'),
    path('universal', views.universal, name='universal'),
    path('faq', views.faq, name='faq')
]

src/plots/forms.py
from django import forms
from multiupload.fields import MultiFileField
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator

from django import forms
from django.core.exceptions import ValidationError

class AbsForm(forms.Form):
    abs_files = MultiFileField(min_num=1, max_num=10, 
                               label="Abs Files",
                               )
        
    abs_labels = forms.CharField(
                        widget=forms.TextInput(
                            attrs={'placeholder': 'Label 1, Label 2 ...'}),
                        label="Abs Labels",
                        required=False
                        ) 

    pl_files = MultiFileField(min_num=1, max_num=10,
                            label="PL Files",
                            required=False
                            )
    
    pl_labels = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Label 1, Label 2 ...'}),
                        label="PL Labels",
                        required=False
                        )
    
    norm_num_abs = forms.IntegerField(widget=forms.TextInput(
        attrs={'placeholder': 'Default value is y max'}),
        label='Normalize to x',
        required=False)

    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Abs & PL'}),
                        label='Figure Title',
                        required=False,
                        )

    theme = forms.ChoiceField(required=False, choices=( 
                        ("", "Standard"), 
                        ("dark", "Dark")))

class UniversalForm(forms.Form):
    files = MultiFileField(min_num=1, max_num=10, 
                               label="Files",
                               )
        
    labels = forms.CharField(
                        widget=forms.TextInput(
                            attrs={'placeholder': 'Label 1, Label 2 ...'}),
                        label="Labels",
                        required=False
                        ) 

    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Figure Title'}),
                        label='Figure Title',
                        required=False,
                        )

    theme = forms.ChoiceField(required=False, choices=( 
                        ("", "Standard"), 
                        ("dark", "Dark")))

class FTIRForm(forms.Form):
    ftir_files = MultiFileField(min_num=1, max_num=10, 
                               label="FTIR Files",
                               )
        
    ftir_labels = forms.CharField(
                        widget=forms.TextInput(
                            attrs={'placeholder': 'Label 1, Label 2 ...'}),
                        label="FTIR Labels",
                        required=False
                        ) 

    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'FTIR'}),
                        label='Figure Title',
                        required=False,
                        )

    theme = forms.ChoiceField(required=False, choices=( 
                        ("", "Standard"), 
                        ("dark", "Dark")))

class XrdForm(forms.Form):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['card_files'] = MultiFileField(
            min_num=1,
            max_num=10,
            label="Card Files",
            required=False
        )
        
        self.fields['card_file_labels'] = forms.CharField(
            widget=forms.TextInput(attrs={
                'class': 'cardfile_labels-input',
                'placeholder': 'Label 1, Label 2 ...'
                }),
            label="Card Labels",
            required=False
        )
        
        self.fields['xrd_files'] = MultiFileField(
            min_num = 1,
            max_num=10,
            label='Xrd Files',
        )

        self.fields['xrd_labels'] = forms.CharField(
                        widget=forms.TextInput(
                            attrs={
                                'placeholder': 'Label 1, Label 2 ...'
                                }),
                        label="Xrd Labels",
                        required=False
                        )
        
        self.fields['title'] = forms.CharField(
                        widget=forms.TextInput(
                            attrs={
                                'class': 'title-input',
                                'placeholder': 'Powder XRD'
                                   }),
                        label='Figure Title',
                        required=False,
                        help_text=''
                        )
        
        self.fields['theme'] = forms.ChoiceField(required=False, choices=( 
                    ("", "Standard"), 
                    ("dark", "Dark")))

class PLQYForm(forms.Form):
    cor_file = MultiFileField(min_num=0, max_num=10, 
                               label="Correction File",
                               )
        
    cor_label = forms.CharField(
                        widget=forms.TextInput(
                        attrs={'placeholder': 'Correction'}),
                        label="Correction Label",
                        required=False
                        )

    blk_file = MultiFileField(min_num=1, max_num=10, 
                               label="Blank File",
                               )
        
    blk_label = forms.CharField(
                        widget=forms.TextInput(
                        attrs={'placeholder': 'Blank'}),
                        label="Blank Label",
                        required=False
                        ) 

    sct_file = MultiFileField(min_num=0, max_num=10,
                            label="Scatter File",
                            required=False
                            )
    
    sct_label = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Scatter'}),
                        label="Scatter Label",
                        required=False
                        )

    emi_file = MultiFileField(min_num=0, max_num=10,
                            label="Emission File",
                            required=False
                            )
    
    emi_label = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Emission'}),
                        label="Emission Label",
                        required=False
                        )

    checkbox = forms.BooleanField(
        label="Check to neglect reabsorption correction",
        required=False,
    )

    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'PLQY'}),
                        label='Figure Title',
                        required=False,
                        )

    theme = forms.ChoiceField(required=False, choices=( 
                        ("", "Standard"), 
                        ("dark", "Dark")))

src/plots/views.py
from django.shortcuts import render, redirect
from .forms import AbsForm, XrdForm, PLQYForm, FTIRForm, UniversalForm
from django.http import JsonResponse
from logic import bokehPlots as bpl
# Create your views here.

def faq(request):
    return render(request, 'pages/faq.html', {})

def home(request):
    abs_path = 'static/files/AbsPl/Absorbance.txt'
    pl_path = 'static/files/AbsPl/Photoluminesence.txt'
    
    abs_label = 'Abs'
    pl_label = 'PL'
    
    card_path ='static/files/Xrd/CsPbBr3_ortho_pnma.txt'
    xrd_path = 'static/files/Xrd/xrd.txt'

    card_label = 'Orthorhombic'
    xrd_label = 'XRD 1'

    theme = '' 

    p = bpl.abspl_plotter([abs_path], [pl_path], [abs_label], [pl_label], theme=theme)
    p2 = bpl.xrd_plotter([card_path], [xrd_path], [card_label], [xrd_label], theme=theme)
    
    vars = {'p1': p[0], 'p2': p[1], 
            'p3': p2[0], 'p4': p2[1]}
    return render(request, 'pages/home2.html', vars)

def abspl(request):
    if request.method == 'POST':
        form = AbsForm(request.POST, request.FILES)
        if form.is_valid():
            print('form', form)
            # # Abs file handle
            # abs_files = request.FILES.getlist('abs_files')
            # input_abs_labels = form.cleaned_data.get('abs_labels')
            # abs_labels = input_abs_labels.split(',') if input_abs_labels else [f'Abs {i+1}' for i in range(len(abs_files))]

            # # PL file handle
            # pl_files = request.FILES.getlist('pl_files')
            # input_pl_labels = form.cleaned_data.get('pl_labels')
            # pl_labels = input_pl_labels.split(',') if input_pl_labels else [f'PL {i+1}' for i in range(len(pl_files))]

            # norm_num_abs = form.cleaned_data.get('norm_num_abs') or None
            # title = form.cleaned_data.get('title') or 'Absorbance & Photoluminescence'
            # theme = form.cleaned_data.get('theme')

            # p = bpl.abspl_plotter(abs_files, pl_files, abs_labels, pl_labels, norm_num_abs, title=title, theme=theme)
            # vars = {'p1': p[0], 'p2': p[1], 'title': title}
            return render(request, 'pages/plot.html', vars)
        else:
            vars = {'form': form}
            return render(request, 'pages/upload.html', vars)
    else:
        form = AbsForm()
        title = 'Absorbance and Photoluminescence'
        vars = {'form': form, 'title': title, 'plot_type': '/abspl'}
        return render(request, 'pages/upload.html', vars)

def xrd(request):
    if request.method == 'POST':
        form = XrdForm(request.POST, request.FILES)
        if form.is_valid():
            # Card file handle
            cardFiles = request.FILES.getlist('card_files')
            card_input_labels = form.cleaned_data.get('card_file_labels')
            card_labels = card_input_labels.split(',') if card_input_labels else [f'Card {i+1}' for i in range(len(cardFiles))]
            
            # XRD file handle
            xrd_files = request.FILES.getlist('xrd_files')
            xrd_input_labels = form.cleaned_data.get('xrd_labels')
            xrd_labels = xrd_input_labels.split(',') if xrd_input_labels else [f'xrd {i+1}' for i in range(len(xrd_files))]            
 
            title = form.cleaned_data.get('title') or 'Powder XRD'
            theme = form.cleaned_data.get('theme')

            p = bpl.xrd_plotter(cardFiles, xrd_files, card_labels, xrd_labels, title, theme=theme)
            vars = {'p1': p[0], 'p2': p[1], 'title': title}
            return render(request, 'pages/plot.html', vars)
        else:            
            vars = {'form': form}
            return render(request, 'pages/upload.html', vars)
    else:
        form = XrdForm()
        title = 'Powder X-ray Diffraction'
        vars = {'form': form, 'title': title, 'plot_type': '/pxrd'}
        return render(request, 'pages/upload.html', vars)

def ftir(request):
    if request.method == 'POST':
        form = FTIRForm(request.POST, request.FILES)
        if form.is_valid():
            # Abs file handle
            ftir_files = request.FILES.getlist('ftir_files')
            input_ftir_labels = form.cleaned_data.get('ftir_labels')
            ftir_labels = input_ftir_labels.split(',') if input_ftir_labels else [f'FTIR {i+1}' for i in range(len(ftir_files))]

            title = form.cleaned_data.get('title') or 'FTIR'
            theme = form.cleaned_data.get('theme')

            p = bpl.ftir_plotter(ftir_files, ftir_labels, title, theme=theme)
            vars = {'p1': p[0], 'p2': p[1], 'title': title}
            return render(request, 'pages/plot.html', vars)
        else:
            vars = {'form': form}
            return render(request, 'pages/upload.html', vars)
    else:
        form = FTIRForm()
        title = 'FTIR'
        vars = {'form': form, 'title': title, 'plot_type': '/ftir'}
        return render(request, 'pages/upload.html', vars)

def plqy(request):
    if request.method == 'POST':
        form = PLQYForm(request.POST, request.FILES)
        if form.is_valid():
            # Correction file handle
            cor_file = request.FILES.getlist('cor_file')
            input_cor_label = form.cleaned_data.get('cor_label')
            cor_label = input_cor_label.split(',') if input_cor_label else [f'Blank {i+1}' for i in range(len(cor_file))]

            # Blank file handle
            blk_file = request.FILES.getlist('blk_file')
            input_blk_label = form.cleaned_data.get('blk_label')
            blk_label = input_blk_label.split(',') if input_blk_label else [f'Blank {i+1}' for i in range(len(blk_file))]

            # Scatter file handle
            sct_file = request.FILES.getlist('sct_file')
            input_sct_label = form.cleaned_data.get('sct_label')
            sct_label = input_sct_label.split(',') if input_sct_label else [f'Scatter {i+1}' for i in range(len(sct_file))]

            # Emission file handle
            emi_file = request.FILES.getlist('emi_file')
            input_emi_label = form.cleaned_data.get('emi_label')
            emi_label = input_emi_label.split(',') if input_emi_label else [f'Emission {i+1}' for i in range(len(emi_file))]
            
            reabsorbance_checkbox = form.cleaned_data.get('checkbox') or False

            title = form.cleaned_data.get('title') or 'Quantum Yield'
            theme = form.cleaned_data.get('theme')
            
            p, plqy = bpl.plqy_plotter(cor_file, blk_file, sct_file, emi_file, cor_label, blk_label, sct_label, emi_label, reabsorbance_checkbox, title, theme=theme)
            vars = {'p1': p[0], 'p2': p[1], 'title': title, 'plqy': plqy, 'plot_type': '/plqy'}
            return render(request, 'pages/plot.html', vars)
        else:
            vars = {'form': form}
            return render(request, 'pages/upload.html', vars)
    else:
        form = PLQYForm()
        title = 'Quantum Yield'
        vars = {'form': form, 'title': title, 'plot_type': '/plqy'}
        return render(request, 'pages/upload.html', vars)

def universal(request):
    if request.method == 'POST':
        form = UniversalForm(request.POST, request.FILES)
        if form.is_valid():
            # Abs file handle
            files = request.FILES.getlist('files')
            input_labels = form.cleaned_data.get('labels')
            labels = input_labels.split(',') if input_labels else [f'Abs {i+1}' for i in range(len(files))]

            title = form.cleaned_data.get('title') or 'Universal'
            theme = form.cleaned_data.get('theme')

            p = bpl.universal_plotter(files, labels, title=title, theme=theme)
            vars = {'p1': p[0], 'p2': p[1], 'title': title}
            return render(request, 'pages/plot.html', vars)
        else:
            vars = {'form': form}
            return render(request, 'pages/upload.html', vars)
    else:
        form = UniversalForm()
        title = 'Universal'
        vars = {'form': form, 'title': title}
        return render(request, 'pages/upload.html', vars)

src/templates/pages/faq.html
{% extends 'base.html' %}
{% load static%}

{% block content %}
<section class="mt-20 bg-white dark:bg-dk-m">
    <div class="py-8 px-4 mx-auto max-w-screen-xl sm:py-16 lg:px-6">
        <h2 class="mb-8 text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Frequently asked questions</h2>
        <div class="grid pt-8 text-left border-t border-gray-200 md:gap-16 dark:border-gray-700 md:grid-cols-2">
            
            <!-- LEFT COLUMN -->
            <div>
                <div class="mb-10">
                    <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
                        <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                        How do I make plots?
                    </h3>
                    <p class="text-gray-500 dark:text-gray-400">
                            To make your own plots, navigate to one of the available plot-types such as,
                        <a href="/abspl" class="font-medium underline text-primary-600 dark:text-primary-500 hover:no-underline" target="_blank" rel="noreferrer">
                            Absorbance and Photoluminesence</a>. Select and upload your data, then fill in the 'label' 
                            section with the name you would like to see in the legend of your plot. Make a comma
                            separated list of labels if there are multiple files.
                    </p>
                </div>
            </div>

            <!-- RIGTH COLUMN -->
            <div>
                <div class="mb-10">
                    <h3 class="flex items-center mb-4 text-lg font-medium text-gray-900 dark:text-white">
                        <svg class="flex-shrink-0 mr-2 w-5 h-5 text-gray-500 dark:text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg>
                        What type of data can I use for plotting?
                    </h3>
                    <p class="text-gray-500 dark:text-gray-400">
                        Currently, our platform supports the following file formats: 
                        .txt, .csv, .ssdat, and .xy. We continuously update our platform 
                        to extract relevant data from uploaded files. While files can 
                        contain non-numerical information, our algorithm skips lines with 
                        non-numerical data. For the smoothest experience, we recommend 
                        uploading files with two distinct columns using common delimiters 
                        like space, comma, or semicolon.
                    </p>
                </div>
            </div>
        </div>
    </div>
  </section>
{% endblock %}

{% block footer %}
{% include 'footer.html'%}
{% endblock %}

src/templates/pages/home.html
{% extends 'base.html' %}
{% load static %}

<!-- ############################## Title ############################## -->
{% block title %}Sciplot{% endblock %}

<!-- ############################## customStyles ############################## -->
{% block customStyles%}
<style>
.figure-container {
  /* border: 1px solid rgb(0, 162, 255); */
  margin-top: 25px;
  min-width: 400px;
  max-width: 1000px;
  margin: auto;
  border: 1px solid var(--post-borderline);
  border-radius: var(--border-radius);
  resize: both;
  overflow: visible;
  display: block;
  justify-content: center;
  transition: 0.2s border;
}
.figure-container:hover {
  border: 1px solid var(--post-hover-borderline);
}
.graph-title-container {
  padding-top: 5px;
}
.graph-title {
  border: 1px solid var(--post-borderline);
  width: 150px;
  display: flex;
  justify-content: center;
  margin: auto;
  text-align: center;
}
.graph-title:hover {
  border: 1px solid var(--post-hover-borderline);
}
.y-axis-graph-container {
  /* border: 1px solid red; */
  display: flex;
}
.graph-container {
  /* border: 1px solid red; */
  min-width: 200px;
  min-height: 400px;
  width: 100%;
  height: 600px;
  padding: 5px;
  margin: 5px;
  /* margin-left: 15px; */
  /* padding-right: 15px; */
}
.graph {
  border: 1px solid var(--post-borderline);
  border-radius: 4px;
  width: 100%;
  height: 100%;
}
.graph:hover {
  border: 1px solid var(--post-hover-borderline);
}
.y-axis-container {
  /* border: 1px solid red; */
  display: inline-flex;
  justify-content: center;
  align-items: center;
  width: 50px;
}
.y-axis {
  border: 1px solid var(--post-borderline);
  text-align: center;
  width: 150px;
  transform: rotate(-90deg);
}
.y-axis:hover {
  border: 1px solid var(--post-hover-borderline);
}
.x-axis-container {
  display: block;
  padding-bottom: 5px;
}
.x-axis {
  border: 1px solid var(--post-borderline);
  text-align: center;
  display: flex;
  margin: auto; 
  width: 150px;
}
.x-axis:hover {
  border: 1px solid var(--post-hover-borderline);
}
.home-content {
    /* border: 1px solid var(--post-borderline); */
    border-radius: 5px;
    max-width: 800px;
    /* margin-top: 200px; */
    margin: auto;
    padding: 20px;
    text-align: center;
}
.home-images {
    border: 1px solid var(--post-borderline);
    display: block;
    margin: auto;
    width: 600px;
    height: 400px;
    border-radius: 10px;
}
.home-paragraph {
    margin-bottom: 20px;
}
.jh-bg-img {
    background-image: url("{% static 'img/bg_lt_1.jpg' %}");
  }
</style>
{% endblock %}

<!-- ############################## customJS ############################## -->
{% block customJS %}
<link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
{% endblock %}

<!-- ############################## Content ############################## -->
{% block content %}
<div>
  <!-- class="rounded-md max-w-screen-md mx-auto pt-20 text-center" -->

  <div class="mt-20">
    <h1 class="mb-4 text-black dark:text-white text-4xl font-extrabold tracking-tight leading-none md:text-5xl lg:text-6xl">
      Your Data
      <span id="element" class="text-transparent bg-clip-text bg-gradient-to-r to-accent-l from-accent-r">
      </span> 
    </h1>
  </div>

  <p class="text-lg font-normal text-gray-500 lg:text-xl dark:text-gray-400">
    Here at Flowbite we focus on markets where technology, innovation, and capital can 
    unlock long-term value and drive economic growth.
  </p>


  <p class="text-lg font-normal text-gray-500 lg:text-xl dark:text-gray-400">
    Our platform is designed to provide users with an intuitive interface for uploading data, 
    and generate interactive plots that give insights into their data.

    Our platform is meticulously crafted to offer users a seamless experience when uploading their data. We understand the importance of simplicity and efficiency, which is why our interface is intuitive and user-friendly. With just a few clicks, users can effortlessly upload their datasets, regardless of format or size.

    Once the data is uploaded, our platform goes to work, leveraging cutting-edge algorithms and visualization techniques to generate interactive plots. These plots are more than just static visualizations; they're dynamic tools that empower users to explore their data in depth. With features such as zoom, pan, and filter, users can interact with the plots, uncovering hidden patterns, trends, and correlations that may have otherwise gone unnoticed.

    But our commitment doesn't stop there. We believe in democratizing data analysis, which is why our platform provides users with actionable insights derived from their data. Whether it's identifying outliers, suggesting data transformations, or recommending statistical tests, our platform equips users with the knowledge they need to make informed decisions.

    In essence, our platform isn't just about data visualization; it's about empowerment. It's about giving users the tools they need to unlock the full potential of their data and drive meaningful outcomes. With our intuitive interface and interactive plots, users can transform raw data into actionable insights, empowering them to make informed decisions and drive success.
  </p>
  
  <hr class="w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700">

  <p class="mt-4 text-transparent text-3xl bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">
    Absorbance & Photoluminesence Plot
  </p>
  <div class="figure-container">
    <div class="h-auto">
    <div class="y-axis-graph-container">
      <div class="graph-container">
        <div class="graph">
          {{ p2 | safe }}
          {{ p1 | safe }}
        </div>
      </div>
    </div>
  </div>

  <hr class="w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700">

  <p class="text-transparent text-3xl bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">
    Powder X-ray Diffractogram
  </p>
    <div class="figure-container">
      <div class="y-axis-graph-container">
        <div class="graph-container">
          <div class="graph">
            {{ p4 | safe }}
            {{ p3 | safe }}
          </div>
        </div>
      </div>
    </div>
  </div>
</div> 
{% endblock content %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

{% block customJSfooter %}
<script src="https://unpkg.com/typed.js@2.1.0/dist/typed.umd.js"></script>
<script>
  var title = new Typed('#element', {
    strings: ['Rendered', 'Visualized', 'Reimagined'],
    typeSpeed: 100,
    backSpeed: 100,
    loop: true,
  });
</script>
{% endblock %}

src/templates/pages/privacypolicy.html
{% extends 'base.html' %}
{% load static%}

{% block content %}

{% endblock %}

{% block footer %}
{% include 'footer.html'%}
{% endblock %}

src/templates/pages/upload.html
{% extends 'base.html' %}

{% load static %}


<!-- ############################## Title ############################## -->
{% block title %}{{ title }}{% endblock %}


<!-- ############################## customStyles ############################## -->
{% block customStyles%}
<style>

#uploadForm {
  margin-top: 25px;
}

/* Style the input elements */
#uploadForm input {
  /* Add your desired styles here */
  width: 60%;
}
#uploadForm p {
  text-align: center;
}

/* Custom Select Styles */
#id_theme {
  appearance: none;
  -webkit-appearance: none;
  -moz-appearance: none;
  background-color: var(--background-color);
  color: var(--text-color);
  border: 2px solid var(--primary-color);
  padding: 10px;
  border-radius: 5px;
  font-size: 16px;
  width: 200px; /* Adjust as needed */
}

#id_theme:focus {
  outline: none;
}

/* Styling the options */
#id_theme option {
  background-color: #1e1e1e;
  color: #fff;
}

/* Styling the selected option */
#id_theme option:checked {
  background-color: #007bff;
}

</style>
{% endblock %}

<!-- ############################## customJS ############################## -->
{% block customJS %}

<script>
function clearInputFile(f) {
if (f.value) {
  try {
    f.value = ''; // For IE11, latest Chrome/Firefox/Opera...
  } catch (err) { }
  if (f.value) { // For IE5 ~ IE10
    var form = document.createElement('form');
    var parentNode = f.parentNode;
    var ref = f.nextSibling;
    form.appendChild(f);
    form.reset();
    parentNode.insertBefore(f, ref);
  }
}
}
</script>
{% if plot_type == "/pxrd" %}
<script>
  document.addEventListener('DOMContentLoaded', function() {
  var clearFilesBtn = document.getElementById('clearFilesBtn');
  var cardFilesInput = document.getElementById('id_card_files');
  var xrdFilesInput = document.getElementById('id_xrd_files');

  clearFilesBtn.addEventListener('click', function() {
    clearInputFile(cardFilesInput);
    clearInputFile(xrdFilesInput);
  });
});
</script>
{% elif plot_type == "/abspl" %}
<script>
document.addEventListener('DOMContentLoaded', function() {
  var clearFilesBtn = document.getElementById('clearFilesBtn');
  var absFilesInput = document.getElementById('id_abs_files');
  var plFilesInput = document.getElementById('id_pl_files');

  clearFilesBtn.addEventListener('click', function() {
    clearInputFile(absFilesInput);
    clearInputFile(plFilesInput);
  });
});
</script>
{% elif plot_type == "/ftir" %}
<script>
document.addEventListener('DOMContentLoaded', function() {
  var clearFilesBtn = document.getElementById('clearFilesBtn');
  var absFilesInput = document.getElementById('id_ftir_files');

  clearFilesBtn.addEventListener('click', function() {
    clearInputFile(absFilesInput);
  });
  });
</script>
{% elif plot_type == "/plqy" %}
<script>
document.addEventListener('DOMContentLoaded', function() {
  var clearFilesBtn = document.getElementById('clearFilesBtn');
  var c = document.getElementById('id_cor_file');
  var b = document.getElementById('id_blk_file');
  var s = document.getElementById('id_sct_file');
  var e = document.getElementById('id_emi_file');

  clearFilesBtn.addEventListener('click', function() {
    clearInputFile(c);
    clearInputFile(b);
    clearInputFile(s);
    clearInputFile(e);
  });
});
</script>
{% endif %}

{% endblock %}

<!-- ############################## headerbutton ############################## -->
{% block headerbutton %}
<a class="header-button" href="/">Home</a>
{% endblock %}

<!-- ############################## column2 ############################## -->
{% block content %}
<h2 style="text-align: center;">
  Upload
</h2>
<h3 style="text-align: center;">
  {% if plot_type == "/abspl" %}
    Absorbance and Photoluminescence
  {% elif plot_type == "/pxrd" %}
    Powder XRD
  {% elif plot_type == "/ftir" %}
    FTIR
  {% elif plot_type == "/plqy" %}
    Quantum Yield
  {% else %}
    {{ title }}
  {% endif %}
</h3>

<form id="uploadForm" enctype="multipart/form-data" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <div style="display: flex; justify-content: center; align-items: center;">
    <div>
      <button id="clearFilesBtn" class="btn"  type="button">Clear Files</button>
      <button class="btn" type="submit">Upload</button>
    </div>
  </div>
</form>

{% endblock %}